name: 'Upload'
description: 'Upload files to Google Drive'
inputs:
  docker-image:
    description: "Docker image to execute latexmk command"
    required: true
  
  workdir:
    description: "Working directory in "
    required: false
    default: /work

  build-files:
    description: "List of TeX files separated by lines to build"
    required: true

  latexmk-options:
    required: false

runs:
  using: 'docker'
  image: docker://docker:stable-dind-rootless
  env:
    WORKDIR: ${{ inputs.workdir }}
    BUILD_FILES: ${{ inputs.build-files }}
    LATEXMK_OPTIONS: ${{ inputs.latexmk-options }}
  args:
    - sh
    - -c
    - echo $BUILD_FILES | xargs -I{} -t sh -c 'TEX_PATH="{}"; cd $(dirname {}); latexmk ${{ inputs.latexmk-options }} "$TEX_PATH"'
