name: 'Build with latexmk'
description: 'Upload files to Google Drive'
inputs:
  docker-image:
    description: "Docker image to execute latexmk command"
    required: true
  
  workdir:
    description: "Working directory in "
    required: false
    default: /work

  build-files:
    description: "List of TeX files separated by lines to build"
    required: true

  latexmk-options:
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    WORKDIR: ${{ inputs.workdir }}
    BUILD_FILES: ${{ inputs.build-files }}
    LATEXMK_OPTIONS: ${{ inputs.latexmk-options }}