name: Build LaTeX on any Docker image
description: |
  Multiple file builds are supported.
#   You can use not only latexmk but also pacdoc etc.

inputs:
  docker-image:
    description: Docker image to execute compile command
    required: true

  build-files:
    description: List of relative paths of TeX files to build, separated by lines
    required: true

  host-workspace:
    description: Absolute path of the host VM directory where the files to be built are located
    required: false

  build-entrypoint:
    description: Entrypoint of Docker container to be started at compile
    required: false

  build-args:
    description: Extra arguments used with the compile command.
    required: false

branding:
  icon: file-text
  color: orange

runs:
  using: docker
  image: docker://satackey/action-latex:v2.0.0
  env:
    BUILD_IMAGE: ${{ inputs.docker-image }}
    BUILD_FILES: ${{ inputs.build-files }}
    HOST_WORKSPACE: ${{ inputs.host-workspace }}
    BUILD_ENTRYPOINT: ${{ inputs.build-entrypoint }}
    BUILD_ARGS: ${{ inputs.build-args }}
