name: 'Build LaTeX with any Docker image'
description: 'Upload files to Google Drive'

inputs:
  docker-image:
    description: 'Docker image to execute latexmk command'
    required: true

  build-files:
    description: 'List of TeX files separated by lines to build'
    required: true

  host-workspace:
    description: 'Location of directory to build'
    required: false

  container-workdir:
    description: 'Working directory in container'
    required: false
    default: /work

  latexmk-options:
    required: false

branding:
  icon: file-text
  color: green

runs:
  using: docker
  image: Dockerfile
  env:
    BUILD_IMAGE: ${{ inputs.docker-image }}
    HOST_WORKSPACE: ${{ inputs.host-workspace }}
    WORKDIR: ${{ inputs.container-workdir }}
    BUILD_FILES: ${{ inputs.build-files }}
    LATEXMK_OPTIONS: ${{ inputs.latexmk-options }}